### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by shresdee** [chaudhary6-1/GameZone#1]
Hello Good morning,
I was unable to view the develop branch and create the new file "docs". Please look at it and provide me the access
Thank you

**Comment by chaudhary6-1** [comment]
Have you accepted the invitation as collaborator?

**Comment by Albrenik** [comment]
after accepting the invitation you will get acces to the repository. I already created a develop branch so make sure you dont create your own to prevent merge conflicts. I guess the Issue can be closed then.

**Comment by shresdee** [comment]
ok got it thank you
