### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Albrenik** [chaudhary6-1/GameZone#5]
Could you provide us the github-pages for the develop branch. otherwise we cannot use xml files as required. Pls choose develop and docs folder als default

**Comment by chaudhary6-1** [comment]
hi,
I have done that. You should be able to see the website at https://gamezone.ninja

**Comment by chaudhary6-1** [comment]
or https://chaudhary6-1.github.io/GameZone/

**Comment by Albrenik** [comment]
Ok thank you very much
