### ISSUE TITLE
Acces has been blocked

### ISSUE THREAD

**Issue by Albrenik** [chaudhary6-1/GameZone#6]
Access to XMLHttpRequest at 'https://chaudhary6-1.github.io/GameZone/Resources/games.xml' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is the error Code i get when trying to acces the xml file from the git repository. Im not sure what you have to change to make it accessable but it would be very helpful if you could fix this or at least tell me when we could meet up on Discord or something to fix this issue because i cannot test my data on the website currently

**Comment by chaudhary6-1** [comment]
maybe try using "https://gamezone.ninja/Resources/games.xml". 
The error might have been caused by the custom domain name.

**Comment by Albrenik** [comment]
Problem solved with client Issue closed
